# Generated by Django 3.2.6 on 2021-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_user", models.CharField(max_length=100, verbose_name="Ip")),
                (
                    "request_itself",
                    models.CharField(max_length=100, verbose_name="Request"),
                ),
            ],
        ),
    ]
