# Generated by Django 3.2.6 on 2021-08-22 14:20

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("bitbucketapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestslist",
            name="json",
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
