# Generated by Django 3.2.6 on 2021-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bitbucketapi", "0002_requestslist_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(max_length=100, verbose_name="Note")),
            ],
        ),
    ]
